;; -*- coding: utf-8; -*-
(define-abbrev-table
  'global-abbrev-table
  '(
    ;; math/unicode symbols
    ("8in" "∈")
    ("8nin" "∉")
    ("8inf" "∞")
    ("8luv" "♥")
    ("8smly" "☺")
    ("8rh" "☛")
    ("8si" "∑")
    ("8in" "⚠")
    ("8ne1" "⛔")
    ("8ne2" "🚫")
    ("84" "∴")
    ("8th" "⚡")


   ("8tri" "▲")
   ("8tril" "◀")
   ("8trir" "▶")
   ("8trid" "▼")

   ("8square" "■")
   ("8circle" "●")
   ("8diamond" "◆")
    
    ;; star
    ("8s1" "★")
    ("8s2" "☆")
    ("8s3" "⚝")
    ("8s4" "✡")

    ;; hexagrams
    ("8h1"  "⎈" ) 
    ("8h2"  "✽" ) 
    ("8h3"  "✲" ) 
    ("8h4"  "✱" ) 
    ("8h5"  "✻" ) 
    ("8h6"  "✼" ) 
    ("8h7"  "✽" ) 
    ("8h8"  "✡" ) 
    ("8h9"  "✾" ) 
    ("8h10"  "✿" ) 
    ("8h11"  "❀" ) 
    ("8h12"  "❁" ) 
    ("8h13"  "❂" ) 
    ("8h14"  "❃" ) 
    ("8h15"  "❄" ) 
    ("8h16"  "❅" ) 
    ("8h17"  "❆" ) 
    ("8h18"  "❇" ) 
    ;; circles
    ("8c1"  "○")
    ("8c2"  "☉")
    ("8c3"  "◎")
    ("8c4"  "◉")
    ("8c5"  "○")
    ("8c6"  "◌")
    ("8c7"  "◎")
    ("8c8"  "●")
    ("8c9"  "◦")
    ("8c10"  "◯")
    ("8c11"  "⚪")
    ("8c12"  "⚫")
    ("8c13"  "⚬")
    ("8c14"  "❍")
    ("8c15"  "￮")
    ("8c16"  "⊙")
    ("8c17"  "⊚")
    ("8c18"  "⊛")
    ("8c19"  "∙")
    ("8c20"  "∘")
    ;; special circles
    ("8sc1"  "◐") 
    ("8sc2"  "◑") 
    ("8sc3"  "◒") 
    ("8sc4"  "◓") 
    ("8sc5"  "◴") 
    ("8sc6"  "◵") 
    ("8sc7"  "◶") 
    ("8sc8"  "◷") 
    ("8sc9"  "⚆") 
    ("8sc10"  "⚇") 
    ("8sc11"  "⚈") 
    ("8sc12"  "⚉") 
    ("8sc13"  "♁") 
    ("8sc14"  "⊖") 
    ("8sc15"  "⊗") 
    ("8sc16"  "⊘") 
    ;; crosses
    ("8cr1"  "✙")
    ("8cr2"  "♱")
    ("8cr3"  "♰")
    ("8cr4"  "☥")
    ("8cr5"  "✞")
    ("8cr6"  "✟")
    ("8cr7"  "✝")
    ("8cr8"  "†")
    ("8cr9"  "✠")
    ("8cr10"  "✚")
    ("8cr11"  "✜")
    ("8cr12"  "✛")
    ("8cr13"  "✢")
    ("8cr14"  "✣")
    ("8cr15"  "✤")
    ("8cr16"  "✥")

    ;; poker sybmols
    ("8p1"  "♠")
    ("8p2"  "♣")
    ("8p3"  "♥")
    ("8p4"  "♦")
    ("8p5"  "♤")
    ("8p6"  "♧")
    ("8p7"  "♡")
    ("8p8"  "♢")
    ;; special symbols

    ("8ss1"  "▶")
    ("8ss2"  "◈")
    ("8ss3"  "◀")
    ("8ss4"  "☀")
    ("8ss5"  "♼")
    ("8ss6"  "☼")
    ("8ss7"  "☾")
    ("8ss8"  "☽")
    ("8ss9"  "☣")
    ("8ss10"  "§")
    ("8ss11"  "¶")
    ("8ss12"  "‡")
    ("8ss13"  "※")
    ("8ss14"  "✕")
    ("8ss15"  "△")
    ("8ss16"  "◇")

    
    ;; email
    ("8wdy" "wordy-english@yahoogroups.com")

    ;; computing tech
    ("8wp" "Wikipedia")
    ("8ms" "Microsoft")
    ("8g" "Google")
    ("8qt" "QuickTime")
    ("8it" "IntelliType")
    ("8msw" "Microsoft Windows")
    ("8win" "Windows")
    ("8ie" "Internet Explorer")
    ("8ahk" "AutoHotkey")
    ("8pr" "POV-Ray")
    ("8ps" "PowerShell")
    ("8mma" "Mathematica")
    ("8js" "javascript")
    ("8vb" "Visual Basic")
    ("8yt" "YouTube")
    ("8ge" "Google Earth")
    ("8ff" "Firefox")
    ("8sl" "Second Life")
    ("8ll" "Linden Labs")
    ("8ee" "ErgoEmacs")

    ;; normal english words
    ("8alt" "alternative")
    ("8char" "character")
    ("8def" "definition")
    ("8bg" "background")
    ("8kb" "keyboard")
    ("8ex" "example")
    ("8kbd" "keybinding")
    ("8env" "environment")
    ("8var" "variable")
    ("8ev" "environment variable")
    ("8cp" "computer")

    ;; sig
    ("8xl" "Xah Lee")

    ;; url
    ("8uxl" "http://xahlee.org/")
    ("8uxp" "http://xahporn.org/")
    ("8uee" "http://ergoemacs.org/")
    ("8uvmm" "http://VirtualMathMuseum.org/")
    ("8u3dxm" "http://3D-XplorMath.org/")

    ;; emacs regex
    ("8num" "\\([0-9]+?\\)")
    ("8str" "\\([^\"]+?\\)\"")
    ("8curly" "“\\([^”]+?\\)”")

    ;; shell commands
    ("8ditto" "ditto -ck --sequesterRsrc --keepParent src dest")
    ("8im" "convert -quality 85% ")
    ("8ims" "convert -size  -quality 85% ")
    ("8im256" "convert +dither -colors 256 ")
    ("8imf" "find . -name \"*png\" | xargs -l -i basename \"{}\" \".png\" | xargs -l -i  convert -quality 85% \"{}.png\" \"{}.jpg\"")

    ("8f0" "find . -type f -empty")
    ("8f00" "find . -type f -size 0 -exec rm {} ';'")
    ("8chmod" "find . -type f -exec chmod 644 {} ';'")
    ("8chmod2" "find . -type d -exec chmod 755 {} ';'")

    ("8unison" "unison -servercmd /usr/bin/unison c:/Users/xah/web ssh://xah@example.com//Users/xah/web")
    ("8sftp" "sftp xah@xahlee.org")
    ("8ssh" "ssh xah@xahlee.org")
    ("8rsync" "rsync -z -r -v -t --exclude=\"*~\" --exclude=\".DS_Store\" --exclude=\".bash_history\" --exclude=\"**/xx_xahlee_info/*\"  --exclude=\"*/_curves_robert_yates/*.png\" --exclude=\"logs/*\"  --exclude=\"xlogs/*\" --delete --rsh=\"ssh -l xah\" ~/web/ xah@example.com:~/")

    ("8rsync2" "rsync -r -v -t --delete --rsh=\"ssh -l xah\" ~/web/ xah@example.com:~/web/")
    ("8rsync3" "rsync -r -v -t --delete --exclude=\"**/My *\" --rsh=\"ssh -l xah\" ~/Documents/ xah@example.com:~/Documents/")
    ))

;; stop asking whether to save newly added abbrev when quitting emacs
;;(setq save-abbrevs nil)

;; turn on abbrev mode globally
(setq-default abbrev-mode t)

